### ISSUE TITLE
"on: workflow_run" support: providing issue number manually

### ISSUE THREAD

**Issue by Akuli** [kanga333/comment-hider#26]
I wanted to use this action with `on: workflow_run`, like this: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

But then it couldn't access the issue number (actually, pull request number), which must be provided as an explicit input to each actions when using `on: workflow_run`.

I started working on a PR that adds  an `issue_number` input, so that you could do something like this, assuming the issue number is stored in `issue_number.txt`:

```yml
- name: Read PR number
  id: issue-number
  run: echo "::set-output name=issueNumber::$(cat issue_number.txt)"
- uses: kanga333/comment-hider@...  # version tag or full commit hash
  name: Hide old comments
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    issue_number: ${{ steps.issue-number.outputs.issueNumber }}
```

The problem is that it takes two steps to first make the issue number available in `${{ ... }}` syntax, and then to call the comment hider. Alternatively, the comment hider could read the issue number from a file:

```yml
- uses: kanga333/comment-hider@...  # version tag or full commit hash
  name: Hide old comments
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    issue_number_file: issue_number.txt
```

Which way is better?
